### ISSUE TITLE
502 Bad Gateway: FastCCI server is down

### ISSUE THREAD

**Issue by octos** [Commonists/fastcci#11]
The server for FastCCI has been down since at least 2020-12-11. See here: [https://fastcci1.wmflabs.org/status](https://fastcci1.wmflabs.org/status)

**Comment by dschwen** [comment]
What the hell. The instances have been deleted. I requested them to be retained :-(

**Comment by dschwen** [comment]
It's back up and running. Instances were only shut down not deleted!

**Comment by dschwen** [comment]
Well, turns out I didn't request the VMs to be retained this time around. I missed a bunch of emails alerting me to that fact. It is sorted out for now and I need to be more attentive to the announcement list...
