### ISSUE TITLE
Commons Good pictures "Connecting..." Indefinitely

### ISSUE THREAD

**Issue by Jeff-Gdot** [Commonists/fastcci#4]
Steps to reproduce: Go to a category like https://commons.wikimedia.org/wiki/Category:Mycalesis_junonia . Click "Good pictures" near the top right corner. Wait. Forever.

See also https://commons.wikimedia.org/wiki/Commons:Village_pump#Connecting...

Directed here by https://phabricator.wikimedia.org/T179122#3714112 .

**Comment by ByordiShilpa** [comment]
This has now been "connecting..." for 15 minutes. For a category with 3 pictures in it and 1 subcategory with 22 pictures and no subcategories.

Expected result: 25 pictures
Obtained result: 0 pictures

**Comment by dschwen** [comment]
Yeah, this is not satisfactory. There are three backend machines serving this tool, but the client is currently not smart about this and just tries a single backend. I should retry different servers until a working one is found.

**Comment by Jeff-Gdot** [comment]
The status page at https://fastcci1.wmflabs.org/status is timing out with error 502, and attempts to use FastCCI from a category page just hang with 'Connecting...'. I didn't see any notices about this being an issue, and it's been down for at least a day. https://commons.wikimedia.org/wiki/Commons:Help_desk#FastCCI_appears_to_be_down.

**Comment by dschwen** [comment]
Currently hunging down a segmentation fault on startup

**Comment by dschwen** [comment]
Database disconnects occasionally produced truncated datafiles with missing categories (past the end of the file). This would cause segfaults when dereferencing pointers into the nirvana. I'm checking validity of the category indices and I'm avoiding updating the fastcci database when the MySQL extraction step fails at one point (in the middle of a shell pipe - using `set - pipefail` here)

**Comment by dschwen** [comment]
Together with the redeployment of fastcci onto new VMs with a bit more RAM this should hopefully remedy the non-responsiveness.
